DROP INDEX IF EXISTS `content_review_judgments_semantic_unique`;
CREATE UNIQUE INDEX `content_review_judgments_semantic_reviewer_unique` ON `content_review_judgments` (`semantic_review_identity`, `reviewer_user_id`);
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `author_user_id` text REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict;
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `resource_type` text NOT NULL DEFAULT 'CONTENT_REVISION';
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `resource_id` text NOT NULL DEFAULT 'SERVER_RESOLVED';
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `judgment_semantic_identity` text NOT NULL DEFAULT '';
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `owner_user_id` text REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict;
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `material_editor_user_ids_json` text NOT NULL DEFAULT '[]';
ALTER TABLE `content_review_policy_evaluations` ADD COLUMN `material_editor_provenance` text NOT NULL DEFAULT 'UNKNOWN';
CREATE UNIQUE INDEX `content_review_policy_evaluations_judgment_slot_unique` ON `content_review_policy_evaluations` (`judgment_id`, `reviewer_slot`);
CREATE TRIGGER `content_review_policy_evaluations_editor_provenance_check` BEFORE INSERT ON `content_review_policy_evaluations` WHEN NEW.material_editor_provenance NOT IN ('KNOWN', 'UNKNOWN') BEGIN SELECT RAISE(ABORT, 'invalid editor provenance'); END;
