import assert from "node:assert/strict";
import test from "node:test";
import { saveContentFinalReviewAuthority, findExactContentFinalReviewAuthority } from "../db/content-final-review-authority-repository.ts";
import { normalizeContentFinalReviewDecision } from "../lib/policy/content-final-review-authority.ts";
import { isContentFinalReviewCanonicalEligible, isContentFinalReviewPublicationEligible } from "../lib/policy/content-final-review-gates.ts";
import { isAuthorizedFinalReviewActor, recordSecureCodingFinalReviewDecision } from "../lib/services/content-final-review-authority.ts";
import type { DatabaseProvider, DatabaseStatement } from "../db/provider/database-provider.ts";

const candidate = "a".repeat(64);
const subjects = [{ subjectIdentity: "topic-1|topic-1|V1|" + "b".repeat(64), semanticOrdinal: 0 }, { subjectIdentity: "topic-2|topic-2|V1|" + "c".repeat(64), semanticOrdinal: 1 }];
type FakeAuthority = { authority_id: string; contract_version: string; decision_type: string; semantic_decision_hash: string; idempotency_key: string; candidate_identity: string; resource_type: string; scope: string; decision_outcome: "APPROVED" | "REJECTED"; authority_state: "ACTIVE"; publication_authority: "NOT_GRANTED"; actor_user_id: string; actor_role: string; audit_log_id: string; created_at: string };
type FakeSubject = { authority_id: string; subject_identity: string; semantic_ordinal: number };
type FakeAudit = { id: string; actor_user_id: string; action: string; resource_id: string; result: string; metadata_json: string };
function decision(outcome: "APPROVED" | "REJECTED" = "APPROVED") {
  return normalizeContentFinalReviewDecision({ contractVersion: "CONTENT_FINAL_REVIEW_AUTHORITY_V1", decisionType: "CONTENT_FINAL_REVIEW_DECISION", candidateIdentity: candidate, resourceType: "CONTENT_REVISION", scope: "SECURE_CODING_V1", subjects, decisionOutcome: outcome, publicationAuthority: "NOT_GRANTED" });
}

class FakePostgres implements DatabaseProvider {
  readonly kind = "supabase" as const;
  authorities: FakeAuthority[] = [];
  authoritySubjects: FakeSubject[] = [];
  audits: FakeAudit[] = [];
  outage = false;
  async query<Row extends Record<string, unknown>>(statement: DatabaseStatement) { if (this.outage) throw new Error("outage"); if (statement.sql.includes("FROM content_final_review_authorities WHERE candidate_identity")) return { rows: this.authorities.filter((row) => row.candidate_identity === statement.parameters?.[0] && row.resource_type === statement.parameters?.[1] && row.scope === statement.parameters?.[2] && row.authority_state === "ACTIVE") as unknown as Row[], rowCount: 0, metadata: { provider: this.kind } }; if (statement.sql.includes("FROM content_final_review_authority_subjects")) return { rows: this.authoritySubjects.filter((row) => row.authority_id === statement.parameters?.[0]).sort((a, b) => a.semantic_ordinal - b.semantic_ordinal) as unknown as Row[], rowCount: 0, metadata: { provider: this.kind } }; return { rows: [] as Row[], rowCount: 0, metadata: { provider: this.kind } }; }
  async queryOne<Row extends Record<string, unknown>>(statement: DatabaseStatement) { if (this.outage) throw new Error("outage"); if (statement.sql.includes("FROM content_final_review_authorities WHERE idempotency_key")) return (this.authorities.find((row) => row.idempotency_key === statement.parameters?.[0]) ?? null) as Row | null; if (statement.sql.includes("FROM content_final_review_authorities WHERE semantic_decision_hash")) return (this.authorities.find((row) => row.semantic_decision_hash === statement.parameters?.[0]) ?? null) as Row | null; if (statement.sql.includes("FROM content_final_review_authorities WHERE authority_id")) return (this.authorities.find((row) => row.authority_id === statement.parameters?.[0]) ?? null) as Row | null; if (statement.sql.includes("FROM admin_audit_logs")) return (this.audits.find((row) => row.id === statement.parameters?.[0]) ?? null) as Row | null; return null; }
  async execute() { return { affectedRows: 0, returnedRows: [], metadata: { provider: this.kind } }; }
  async transaction(statements: readonly DatabaseStatement[]) { if (this.outage) throw new Error("outage"); const staged = { authorities: [...this.authorities], authoritySubjects: [...this.authoritySubjects], audits: [...this.audits] }; for (const statement of statements) { const p = statement.parameters ?? []; const s = (index: number) => String(p[index]); const n = (index: number) => Number(p[index]); if (statement.sql.includes("INSERT INTO admin_audit_logs")) staged.audits.push({ id: s(0), actor_user_id: s(1), action: s(3), resource_id: s(5), result: "SUCCESS", metadata_json: s(7) }); else if (statement.sql.includes("INSERT INTO content_final_review_authorities (")) { if (staged.authorities.some((row) => row.idempotency_key === s(4) || row.semantic_decision_hash === s(3))) throw new Error("unique"); staged.authorities.push({ authority_id: s(0), contract_version: s(1), decision_type: s(2), semantic_decision_hash: s(3), idempotency_key: s(4), candidate_identity: s(5), resource_type: s(6), scope: s(7), decision_outcome: s(8) as "APPROVED" | "REJECTED", authority_state: "ACTIVE", publication_authority: "NOT_GRANTED", actor_user_id: s(10), actor_role: s(11), audit_log_id: s(12), created_at: s(13) }); } else if (statement.sql.includes("INSERT INTO content_final_review_authority_subjects")) staged.authoritySubjects.push({ authority_id: s(0), subject_identity: s(1), semantic_ordinal: n(2) }); } this.authorities = staged.authorities; this.authoritySubjects = staged.authoritySubjects; this.audits = staged.audits; return []; }
  async healthCheck() { return !this.outage; }
}

test("approved authority is exact, auditable, canonical-eligible, and never publication-eligible", async () => { const db = new FakePostgres(); const result = await saveContentFinalReviewAuthority({ decision: decision(), idempotencyKey: "idempotency-a", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }, db); const found = await findExactContentFinalReviewAuthority(decision(), db); assert.equal(result.outcome, "NEW_AUTHORITY"); assert.ok(found); assert.equal(found.contractVersion, decision().contractVersion); assert.equal(found.decisionType, decision().decisionType); assert.equal(found.semanticDecisionHash, result.authority.semanticDecisionHash); assert.equal(found.candidateIdentity, decision().candidateIdentity); assert.equal(found.resourceType, decision().resourceType); assert.equal(found.scope, decision().scope); assert.equal(found.decisionOutcome, "APPROVED"); assert.equal(found.authorityState, "ACTIVE"); assert.equal(found.publicationAuthority, "NOT_GRANTED"); assert.equal(found.idempotencyKey, "idempotency-a"); assert.equal(found.actorUserId, "reviewer"); assert.equal(found.actorRole, "CONTENT_REVIEWER"); assert.equal(found.auditLogId, result.authority.auditLogId); assert.deepEqual(found.subjects, subjects); assert.equal(isContentFinalReviewCanonicalEligible(found), true); assert.equal(isContentFinalReviewPublicationEligible(), false); });
test("exact retry is idempotent and a reused key with different semantics is denied", async () => { const db = new FakePostgres(); const input = { decision: decision(), idempotencyKey: "idempotency-b", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }; assert.equal((await saveContentFinalReviewAuthority(input, db)).outcome, "NEW_AUTHORITY"); assert.equal((await saveContentFinalReviewAuthority(input, db)).outcome, "IDEMPOTENT_DUPLICATE"); assert.equal((await saveContentFinalReviewAuthority({ ...input, idempotencyKey: "idempotency-b-other" }, db)).outcome, "IDEMPOTENT_DUPLICATE"); await assert.rejects(() => saveContentFinalReviewAuthority({ ...input, decision: decision("REJECTED") }, db), /IDEMPOTENCY_CONFLICT/); });
test("rejected and conflicting authority records never pass exact lookup", async () => { const rejectedDb = new FakePostgres(); await saveContentFinalReviewAuthority({ decision: decision("REJECTED"), idempotencyKey: "idempotency-c", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }, rejectedDb); assert.equal(await findExactContentFinalReviewAuthority(decision(), rejectedDb), null); const conflictDb = new FakePostgres(); await saveContentFinalReviewAuthority({ decision: decision(), idempotencyKey: "idempotency-d", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }, conflictDb); await saveContentFinalReviewAuthority({ decision: decision("REJECTED"), idempotencyKey: "idempotency-e", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }, conflictDb); assert.equal(await findExactContentFinalReviewAuthority(decision(), conflictDb), null); });
test("repository outage fails closed", async () => { const db = new FakePostgres(); db.outage = true; await assert.rejects(() => findExactContentFinalReviewAuthority(decision(), db)); assert.equal(isContentFinalReviewCanonicalEligible(null), false); assert.equal(isContentFinalReviewPublicationEligible(), false); });
test("audit tampering makes an otherwise matching authority unusable", async () => { const db = new FakePostgres(); await saveContentFinalReviewAuthority({ decision: decision(), idempotencyKey: "idempotency-f", actorUserId: "reviewer", actorRole: "CONTENT_REVIEWER" }, db); db.audits[0].metadata_json = "{}"; assert.equal(await findExactContentFinalReviewAuthority(decision(), db), null); });
test("unauthenticated and non-governance actors cannot enter the authority workflow", async () => { assert.equal(isAuthorizedFinalReviewActor(null), false); assert.equal(isAuthorizedFinalReviewActor({ id: "user", email: "user@example.com", displayName: "User", roles: ["LEARNER"] }), false); await assert.rejects(() => recordSecureCodingFinalReviewDecision({ outcome: "APPROVED", confirmed: true, idempotencyKey: "idempotency-g", }, { id: "user", email: "user@example.com", displayName: "User", roles: ["LEARNER"] }, new FakePostgres()), /GOVERNANCE_ROLE_REQUIRED/); });
test("missing explicit human confirmation is denied before persistence", async () => { await assert.rejects(() => recordSecureCodingFinalReviewDecision({ outcome: "APPROVED", confirmed: false, idempotencyKey: "idempotency-h" }, { id: "reviewer", email: "reviewer@example.com", displayName: "Reviewer", roles: ["CONTENT_REVIEWER"] }, new FakePostgres()), /EXPLICIT_CONFIRMATION_REQUIRED/); });
