import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionButton } from "@/components/design-system-primitives";
import { getCourseStatistics } from "@/db/phase3-repositories";
import { getCourseById, getEnrollmentForCourse, listCurriculum } from "@/db/repositories";
import { requireCurrentAppUser } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "과정 분석 | SECURIUM", description: "과정별 정답률과 복습이 필요한 영역을 확인합니다." };

export default async function CourseAnalyticsPage({ params }: { params: Promise<{ courseId: string }> }) {
  const { courseId } = await params; const user = await requireCurrentAppUser(`/analytics/${courseId}`);
  const [course, enrollment, curriculum] = await Promise.all([getCourseById(courseId), getEnrollmentForCourse(user.id, courseId), listCurriculum(courseId)]);
  if (!course || !enrollment) notFound();
  const stats = await getCourseStatistics(user.id, courseId);
  const subjectNames = new Map(curriculum.map((subject) => [subject.id, subject.name]));
  const topicMeta = new Map(curriculum.flatMap((subject) => subject.topics.map((topic) => [topic.id, { name: topic.name, subjectId: subject.id }] as const)));
  const weakTopics = [...stats.byTopic].filter((item) => item.id !== "UNMAPPED").sort((a, b) => a.accuracy - b.accuracy);
  const weakest = weakTopics[0]; const weakestMeta = weakest ? topicMeta.get(weakest.id) : undefined; const practiceHref = weakest ? buildPracticeHref(course.slug, weakest.id, weakestMeta?.subjectId) : `/practice/${course.slug}?count=10`;
  return <main className="page-main dashboard-page"><div className="shell"><header className="dashboard-intro"><div><p className="eyebrow">과정 학습 분석</p><h1>{course.name} 분석</h1><p>문제풀이와 이론 진도를 바탕으로 다음 복습 영역을 확인하세요.</p></div><ActionButton variant="dark" href={`/practice/${course.slug}?count=10`}>문제풀이 시작</ActionButton></header><section className="analytics-overview-panel" aria-label="과정 분석 요약"><div><p className="eyebrow">학습 결과</p><h2>{stats.totalQuestions ? `현재 정답률 ${stats.overallAccuracy}%` : "아직 학습 기록이 없습니다."}</h2><p>{stats.totalQuestions ? "정답률이 낮은 주제를 찾아 복습 행동으로 이어가세요." : "문제를 풀면 과목별 정답률과 취약 주제가 정리됩니다."}</p></div><dl><div><dt>전체 정답률</dt><dd>{stats.overallAccuracy}%</dd></div><div><dt>최근 7일</dt><dd>{stats.recent7Days}문제</dd></div><div><dt>반복 오답</dt><dd>{stats.repeatedWrongCount}개</dd></div><div><dt>단계 완료</dt><dd>{stats.levelCompletionRate}%</dd></div></dl></section><section className="analytics-action-panel" aria-label="취약 영역 추천"><div><p className="eyebrow">먼저 확인할 영역</p><h2>{weakest ? `${weakestMeta?.name ?? "확인할 주제"}부터 복습하세요.` : "문제를 풀고 취약 영역을 찾아보세요."}</h2><p>{weakest ? `현재 정답률은 ${weakest.accuracy}%입니다. 해당 주제 문제부터 다시 풀어보세요.` : "학습 기록이 쌓이면 과목과 주제별 취약 영역을 자동으로 보여드립니다."}</p></div><ActionButton variant="dark" href={practiceHref}>{weakest ? "취약 주제 풀기" : "문제 10개 풀기"}</ActionButton></section><section className="analytics-action-strip section-block" aria-label="분석 다음 행동"><Link className="analytics-action-card analytics-action-card-primary" href={practiceHref}><span>01 · 취약 영역</span><strong>{weakest ? weakestMeta?.name ?? "확인할 주제" : "학습 기록 만들기"}</strong><p>{weakest ? `정답률 ${weakest.accuracy}% 영역부터 보완하세요.` : "문제를 풀면 다음 복습 영역을 추천합니다."}</p></Link><Link className="analytics-action-card" href={`/practice/${course.slug}?count=10`}><span>02 · 추가 문제</span><strong>과정 문제 10개 풀기</strong><p>기록이 쌓일수록 분석이 구체화됩니다.</p></Link><Link className="analytics-action-card" href="/reviews"><span>03 · 복습 연결</span><strong>오늘의 복습 확인</strong><p>반복 오답과 예정 복습을 함께 확인하세요.</p></Link></section><section className="analytics-grid section-block"><Breakdown title="난이도별 정답률" rows={stats.byDifficulty} /><Breakdown title="문제 유형별 정답률" rows={stats.byType} /><Breakdown title="과목별 정답률" rows={stats.bySubject.map((row) => ({ ...row, label: subjectNames.get(row.id) ?? "과목 정보 확인 중", href: row.id === "UNMAPPED" ? undefined : `/practice/${course.slug}?subjectId=${row.id}&count=10` }))} /><Breakdown title="주제별 취약 영역" rows={weakTopics.map((row) => ({ ...row, label: topicMeta.get(row.id)?.name ?? "주제 정보 확인 중", href: buildPracticeHref(course.slug, row.id, topicMeta.get(row.id)?.subjectId) }))} /></section><section className="stats-grid section-block"><Metric label="최근 30일" value={stats.recent30Days} unit="문제" /><Metric label="평균 응답 시간" value={Math.round(stats.averageResponseTime / 1000)} unit="초" /><Metric label="복습 성공률" value={stats.reviewSuccessRate} unit="%" /><Metric label="모의고사 평균" value={stats.mockExamAverageScore} unit="점" /></section></div></main>;
}
function buildPracticeHref(courseSlug: string, topicId: string, subjectId?: string) { const params = new URLSearchParams({ topicId, count: "10" }); if (subjectId) params.set("subjectId", subjectId); return `/practice/${courseSlug}?${params.toString()}`; }
function Metric({ label, value, unit }: { label: string; value: number; unit: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{unit}</small></div>; }
function Breakdown({ title, rows }: { title: string; rows: Array<{ id: string; total: number; accuracy: number; label?: string; href?: string }> }) { return <section className="learner-analytics-panel analytics-panel"><h2>{title}</h2>{rows.length ? rows.map((row) => <div className="bar-row analytics-action-row" key={row.id}><div><strong>{row.label ?? "학습 영역"}</strong><span>{row.total}문제 · {row.accuracy}%</span></div><div className="progress-track" aria-label={`${row.label ?? "학습 영역"} 정답률 ${row.accuracy}%`}><span style={{ width: `${row.accuracy}%` }} /></div>{row.href ? <ActionButton href={row.href} variant="ghost">문제 풀기</ActionButton> : null}</div>) : <p>아직 충분한 학습 기록이 없습니다.</p>}</section>; }
