"use client";

import { useMemo, useState } from "react";

type Course = { id: string; name: string; shortName: string; groupName: string };
type SharedContent = { id: string; slug: string; canonicalKey: string; title: string; summary: string; body: string; bodyFormat: string; learningObjectivesJson: string; coreConceptsJson: string; practicalExamplesJson: string; version: string; status: string; updatedAt: string };
type CourseLesson = { id: string; courseId: string; curriculumNodeId: string | null; contentId: string; contentTitle: string; displayTitle: string; sortOrder: number; difficulty: string | null; importance: number | null; estimatedMinutes: number; isRequired: boolean; completionRule: string; status: string; updatedAt: string; extensionId: string | null; extensionLearningObjectivesOverrideJson: string | null; extensionAdditionalBody: string | null; extensionExamPointsJson: string | null; extensionPracticalNotes: string | null; extensionLegalNotes: string | null; extensionStandardNotes: string | null; extensionEvidenceNotes: string | null; extensionCommonMistakes: string | null; extensionInstructorNotes: string | null; extensionVersion: string | null; extensionStatus: string | null };
type CurriculumTree = { id: string; courseId: string; title: string; version: string; status: string };
type CurriculumNode = { id: string; title: string; nodeType: string; depth: number; path: string | null; status: string };
type ContentUsage = { courseLessonId: string; courseId: string; courseName: string; displayTitle: string; status: string };
const statuses = ["DRAFT", "PUBLISHED", "ARCHIVED"] as const;
const bodyFormats = ["MARKDOWN", "STRUCTURED_JSON", "PLAIN_TEXT"] as const;
const completionRules = ["MANUAL", "SCROLL_END", "MINIMUM_REQUIREMENTS"] as const;
const label = (value: string) => ({ DRAFT: "초안", PUBLISHED: "게시됨", ARCHIVED: "보관됨", MANUAL: "수동 완료", SCROLL_END: "본문 끝까지 읽기", MINIMUM_REQUIREMENTS: "최소 조건 충족" }[value] ?? value);
function jsonDefault(value: string | null | undefined) { return value?.trim() || "[]"; }
function optionalId(value: FormDataEntryValue | null) { return typeof value === "string" && value.trim() ? value.trim() : undefined; }

export function AdminSharedContentManager({ courses, contents, courseLessons, curriculumTrees, curriculumNodes, usage, selectedCourseId, selectedContentId, selectedCourseLessonId, selectedCurriculumNodeId }: { courses: Course[]; contents: SharedContent[]; courseLessons: CourseLesson[]; curriculumTrees: CurriculumTree[]; curriculumNodes: CurriculumNode[]; usage: ContentUsage[]; selectedCourseId: string; selectedContentId: string; selectedCourseLessonId: string; selectedCurriculumNodeId: string }) {
  const [contentId, setContentId] = useState(selectedContentId || contents[0]?.id || "");
  const [lessonId, setLessonId] = useState(selectedCourseLessonId || courseLessons[0]?.id || "");
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState("");
  const content = contents.find((item) => item.id === contentId) ?? null;
  const lesson = courseLessons.find((item) => item.id === lessonId) ?? null;
  const filteredContents = useMemo(() => contents.filter((item) => (!query || [item.title, item.slug, item.canonicalKey, item.summary].join(" ").toLowerCase().includes(query.toLowerCase())) && (statusFilter === "ALL" || item.status === statusFilter)), [contents, query, statusFilter]);
  const activeTree = curriculumTrees.find((tree) => tree.status === "ACTIVE") ?? curriculumTrees[0];

  async function submit(operation: string, payload: Record<string, unknown>, pendingLabel: string) {
    if (pending) return;
    setPending(pendingLabel); setMessage("");
    try {
      const response = await fetch("/api/admin/shared-content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operation, ...payload }) });
      const result = await response.json().catch(() => ({})) as { error?: string };
      if (!response.ok) { setMessage(result.error ?? "저장하지 못했습니다. 입력값과 권한을 확인해주세요."); return; }
      window.location.reload();
    } catch { setMessage("네트워크 오류가 발생했습니다. 잠시 후 다시 시도해주세요."); } finally { setPending(""); }
  }
  async function saveContent(form: FormData) { await submit("saveContent", { content: { id: optionalId(form.get("id")), slug: form.get("slug"), canonicalKey: form.get("canonicalKey"), title: form.get("title"), summary: form.get("summary"), body: form.get("body"), bodyFormat: form.get("bodyFormat"), learningObjectivesJson: form.get("learningObjectivesJson"), coreConceptsJson: form.get("coreConceptsJson"), practicalExamplesJson: form.get("practicalExamplesJson"), diagramsJson: "[]", mediaJson: "[]", version: form.get("version"), status: form.get("status") } }, "content-save"); }
  async function saveLesson(form: FormData) { await submit("saveCourseLesson", { courseLesson: { id: optionalId(form.get("id")), courseId: selectedCourseId, curriculumNodeId: form.get("curriculumNodeId"), contentId: form.get("contentId"), displayTitle: form.get("displayTitle"), sortOrder: form.get("sortOrder"), difficulty: form.get("difficulty"), importance: form.get("importance"), estimatedMinutes: form.get("estimatedMinutes"), isRequired: form.get("isRequired") === "on", completionRule: form.get("completionRule"), status: form.get("status") } }, "lesson-save"); }
  async function saveExtension(form: FormData) { await submit("saveCourseLessonExtension", { extension: { id: optionalId(form.get("id")), courseLessonId: form.get("courseLessonId"), learningObjectivesOverrideJson: form.get("learningObjectivesOverrideJson"), additionalBody: form.get("additionalBody"), examPointsJson: form.get("examPointsJson"), practicalNotes: form.get("practicalNotes"), legalNotes: form.get("legalNotes"), standardNotes: form.get("standardNotes"), evidenceNotes: form.get("evidenceNotes"), commonMistakes: form.get("commonMistakes"), instructorNotes: form.get("instructorNotes"), version: form.get("version"), status: form.get("status") } }, "extension-save"); }

  return <div className="curriculum-admin-grid">{message ? <p className="inline-error" role="alert">{message}</p> : null}<section className="admin-panel"><div className="section-heading compact"><div><p className="eyebrow">CONTENT</p><h2>공통 콘텐츠 등록·수정</h2><p>여러 과정에서 재사용하는 공식 학습 원본입니다. 과정별 표시와 보강 설명은 별도로 관리합니다.</p></div><div className="admin-inline-actions"><select aria-label="수정할 공통 콘텐츠 선택" className="admin-inline-select" value={contentId} onChange={(event) => setContentId(event.target.value)}><option value="">새 콘텐츠</option>{contents.map((item) => <option key={item.id} value={item.id}>{item.title} · {label(item.status)}</option>)}</select></div></div><form className="admin-form" action={saveContent}><input name="id" type="hidden" value={content?.id ?? ""} /><label>Slug<input name="slug" required defaultValue={content?.slug ?? ""} placeholder="privacy-access-control" /></label><label>Canonical Key<input name="canonicalKey" required defaultValue={content?.canonicalKey ?? ""} placeholder="privacy.access-control" /></label><label>제목<input name="title" required defaultValue={content?.title ?? ""} placeholder="접근통제 기본 개념" /></label><label>버전<input name="version" required defaultValue={content?.version ?? "1.0.0"} /></label><label>본문 형식<select name="bodyFormat" defaultValue={content?.bodyFormat ?? "MARKDOWN"}>{bodyFormats.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>상태<select name="status" defaultValue={content?.status ?? "DRAFT"}>{statuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="wide">요약<textarea name="summary" rows={2} defaultValue={content?.summary ?? ""} /></label><label className="wide">본문<textarea name="body" rows={8} required defaultValue={content?.body ?? ""} placeholder="Markdown 또는 일반 텍스트 본문을 입력하세요." /></label><label className="wide">학습 목표 JSON 배열<textarea name="learningObjectivesJson" rows={2} defaultValue={jsonDefault(content?.learningObjectivesJson)} /></label><label className="wide">핵심 개념 JSON 배열<textarea name="coreConceptsJson" rows={2} defaultValue={jsonDefault(content?.coreConceptsJson)} /></label><label className="wide">실무 예시 JSON 배열<textarea name="practicalExamplesJson" rows={2} defaultValue={jsonDefault(content?.practicalExamplesJson)} /></label><button className="button button-dark" disabled={pending === "content-save"} type="submit">{pending === "content-save" ? "저장 중…" : content ? "콘텐츠 수정" : "콘텐츠 등록"}</button></form></section>
    <section className="admin-panel"><div className="section-heading compact"><div><p className="eyebrow">COURSE LESSON</p><h2>과정별 CourseLesson 연결·수정</h2><p>{courses.find((course) => course.id === selectedCourseId)?.name ?? "선택된 과정 없음"} · {activeTree ? `${activeTree.title} · ${activeTree.version}` : "커리큘럼 트리 없음"}</p></div><div className="admin-inline-actions"><select aria-label="관리할 과정 선택" value={selectedCourseId} onChange={(event) => { window.location.href = `/admin/shared-content?courseId=${event.target.value}`; }}>{courses.map((course) => <option key={course.id} value={course.id}>{course.groupName} · {course.shortName}</option>)}</select><select aria-label="수정할 CourseLesson 선택" value={lessonId} onChange={(event) => setLessonId(event.target.value)}><option value="">새 CourseLesson</option>{courseLessons.map((item) => <option key={item.id} value={item.id}>{item.displayTitle} · {label(item.status)}</option>)}</select></div></div><form className="admin-form" action={saveLesson}><input name="id" type="hidden" value={lesson?.id ?? ""} /><label>공통 콘텐츠<select name="contentId" required defaultValue={lesson?.contentId ?? contentId}>{contents.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.version}</option>)}</select></label><label>커리큘럼 노드<select name="curriculumNodeId" defaultValue={lesson?.curriculumNodeId ?? selectedCurriculumNodeId}><option value="">노드 연결 안 함</option>{curriculumNodes.map((node) => <option key={node.id} value={node.id}>{"  ".repeat(node.depth)}{node.title} · {node.nodeType}</option>)}</select></label><label>과정 표시 제목<input name="displayTitle" required defaultValue={lesson?.displayTitle ?? content?.title ?? ""} /></label><label>정렬 순서<input name="sortOrder" type="number" min={0} defaultValue={lesson?.sortOrder ?? courseLessons.length * 10 + 10} /></label><label>난이도<input name="difficulty" defaultValue={lesson?.difficulty ?? ""} placeholder="중급" /></label><label>중요도<input name="importance" type="number" min={0} max={100} defaultValue={lesson?.importance ?? ""} /></label><label>예상 학습 시간(분)<input name="estimatedMinutes" type="number" min={1} max={1440} defaultValue={lesson?.estimatedMinutes ?? 10} /></label><label>완료 규칙<select name="completionRule" defaultValue={lesson?.completionRule ?? "MANUAL"}>{completionRules.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>상태<select name="status" defaultValue={lesson?.status ?? "DRAFT"}>{statuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="check-label"><input name="isRequired" type="checkbox" defaultChecked={lesson?.isRequired ?? true} />필수 학습</label><button className="button button-dark" disabled={pending === "lesson-save" || !contents.length} type="submit">{pending === "lesson-save" ? "저장 중…" : lesson ? "CourseLesson 수정" : "CourseLesson 연결"}</button></form></section>
    <section className="admin-panel"><div className="section-heading compact"><div><p className="eyebrow">EXTENSION</p><h2>과정별 보강 설명</h2><p>원본 콘텐츠를 유지하면서 시험 포인트, 실무 메모, 법령·기준 메모를 과정별로 추가합니다.</p></div></div><form className="admin-form" action={saveExtension}><input name="id" type="hidden" value={lesson?.extensionId ?? ""} /><label>CourseLesson<select name="courseLessonId" required value={lessonId} onChange={(event) => setLessonId(event.target.value)}><option value="">CourseLesson 선택</option>{courseLessons.map((item) => <option key={item.id} value={item.id}>{item.displayTitle}</option>)}</select></label><label>버전<input name="version" required defaultValue={lesson?.extensionVersion ?? "1.0.0"} /></label><label>상태<select name="status" defaultValue={lesson?.extensionStatus ?? "DRAFT"}>{statuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="wide">학습 목표 덮어쓰기 JSON<textarea name="learningObjectivesOverrideJson" rows={2} defaultValue={lesson?.extensionLearningObjectivesOverrideJson ?? ""} /></label><label className="wide">추가 본문<textarea name="additionalBody" rows={4} defaultValue={lesson?.extensionAdditionalBody ?? ""} /></label><label className="wide">시험 포인트 JSON<textarea name="examPointsJson" rows={2} defaultValue={jsonDefault(lesson?.extensionExamPointsJson)} /></label><label className="wide">실무 메모<textarea name="practicalNotes" rows={2} defaultValue={lesson?.extensionPracticalNotes ?? ""} /></label><label className="wide">법령 메모<textarea name="legalNotes" rows={2} defaultValue={lesson?.extensionLegalNotes ?? ""} /></label><label className="wide">기준 메모<textarea name="standardNotes" rows={2} defaultValue={lesson?.extensionStandardNotes ?? ""} /></label><label className="wide">근거 메모<textarea name="evidenceNotes" rows={2} defaultValue={lesson?.extensionEvidenceNotes ?? ""} /></label><label className="wide">자주 하는 실수<textarea name="commonMistakes" rows={2} defaultValue={lesson?.extensionCommonMistakes ?? ""} /></label><label className="wide">관리자 메모<textarea name="instructorNotes" rows={2} defaultValue={lesson?.extensionInstructorNotes ?? ""} /></label><button className="button button-dark" disabled={pending === "extension-save" || !lesson} type="submit">{pending === "extension-save" ? "저장 중…" : "보강 설명 저장"}</button></form></section>
    <section className="admin-panel"><h2>공유 콘텐츠 목록</h2><div className="admin-list-toolbar"><label>검색<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="제목, slug, canonical key" /></label><label>상태<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="ALL">전체</option>{statuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><span className="admin-helper">{filteredContents.length}개 결과</span></div><div className="admin-record-list">{filteredContents.length ? filteredContents.map((item) => <article className="admin-record shared-content-record" key={item.id}><div><strong>{item.title}</strong><small>{item.canonicalKey} · {item.version} · {label(item.status)}</small><p>{item.summary || "요약 없음"}</p></div><div className="admin-inline-actions"><button className="button button-ghost" type="button" onClick={() => setContentId(item.id)}>수정</button><a className="button button-ghost" href={`/admin/shared-content?courseId=${selectedCourseId}&contentId=${item.id}`}>사용처 보기</a></div></article>) : <p className="empty-copy">조건에 맞는 공통 콘텐츠가 없습니다.</p>}</div></section>
    <section className="admin-panel"><h2>선택 콘텐츠 사용처</h2><p className="admin-helper">{content ? `${content.title}이(가) 연결된 과정 레슨입니다.` : "사용처를 확인할 콘텐츠를 먼저 선택하세요."}</p><div className="admin-record-list">{usage.length ? usage.map((item) => <article className="admin-record shared-content-record" key={item.courseLessonId}><div><strong>{item.displayTitle}</strong><small>{item.courseName} · {label(item.status)}</small></div></article>) : <p className="empty-copy">아직 연결된 CourseLesson이 없습니다.</p>}</div></section>
  </div>;
}
