import type { Metadata } from "next";
import Link from "next/link";
import { ActionButton } from "@/components/design-system-primitives";
import { LearningSettingsForm } from "@/components/learning-settings-form";
import { ProgressBar } from "@/components/progress-bar";
import { getTodayLearningPlan } from "@/db/phase3-repositories";
import { listDashboardUserEnrollments } from "@/lib/dashboard-enrollments";
import { requireCurrentAppUser } from "@/lib/auth";

export const metadata: Metadata = { title: "대시보드 | SECURIUM" };
export const dynamic = "force-dynamic";
type Enrollment = Awaited<ReturnType<typeof listDashboardUserEnrollments>>[number];

export default async function DashboardPage() {
  const user = await requireCurrentAppUser("/dashboard");
  const [enrollments, planResult] = await Promise.all([safe(() => listDashboardUserEnrollments(user.id), []), safe(() => getTodayLearningPlan(user.id), null)]);
  const plan = planResult ?? emptyPlan();
  const active = enrollments.filter((item) => item.status === "ACTIVE");
  const current = active.slice().sort((a, b) => new Date(b.lastStudiedAt ?? 0).getTime() - new Date(a.lastStudiedAt ?? 0).getTime())[0];
  const recommendation = plan.recommendations[0];
  const next = recommendation ? { href: recommendation.href, title: recommendation.title, reason: recommendation.reason, cta: "추천 학습 시작" } : plan.reviewSummary.dueCount ? { href: "/reviews", title: "오늘의 복습을 시작하세요", reason: `${plan.reviewSummary.dueCount}개의 복습 항목이 기다리고 있습니다.`, cta: "복습 시작" } : current ? { href: `/learn/${current.courseSlug}`, title: `${current.courseName} 이어 학습`, reason: `현재 과정 진도는 ${current.progressPercent}%입니다.`, cta: "학습 이어가기" } : { href: "/courses", title: "첫 학습 과정을 선택하세요", reason: "과정을 선택하면 개인 학습 흐름이 시작됩니다.", cta: "과정 선택" };
  const remaining = Math.max(plan.settings.dailyQuestionGoal - plan.completedQuestions, 0);

  return <main className="page-main dashboard-page"><div className="shell"><section className="dashboard-intro dashboard-hero"><div><p className="eyebrow">오늘의 학습</p><h1>{user.displayName}님, 오늘도 학습을 시작해볼까요?</h1><p>{current ? `${current.courseName}의 다음 학습과 복습을 준비했습니다.` : "과정을 선택하면 진도와 복습 일정을 자동으로 관리할 수 있습니다."}</p><dl className="dashboard-action-rail" aria-label="오늘의 학습 요약"><div><dt>이어서 학습</dt><dd>{current ? `${current.courseName} · ${current.progressPercent}%` : "과정 선택 필요"}</dd></div><div><dt>다음 행동</dt><dd>{next.title}</dd></div><div><dt>오늘의 문제</dt><dd>{remaining}문제 남음</dd></div><div><dt>복습 예정</dt><dd>{plan.reviewSummary.dueCount}개</dd></div></dl><div className="dashboard-next-action"><span className="badge">지금 시작</span><div><strong>{next.title}</strong><p>{next.reason}</p></div><ActionButton href={next.href} variant="primary">{next.cta}</ActionButton></div></div><aside className="dashboard-focus-card" aria-label="오늘의 학습 현황"><span className="badge">오늘의 진행 현황</span><strong>{current?.courseName ?? "학습 과정 선택"}</strong><p>{current ? "학습 기록을 바탕으로 다음 행동을 안내합니다." : "첫 과정을 선택하면 맞춤형 학습 흐름을 시작합니다."}</p><dl className="dashboard-focus-list"><div><dt>오늘 문제</dt><dd>{remaining}문제</dd></div><div><dt>복습 예정</dt><dd>{plan.reviewSummary.dueCount}개</dd></div><div><dt>전체 진도</dt><dd>{current ? `${current.progressPercent}%` : "-"}</dd></div></dl></aside></section>
    <section className="section-block today-plan" aria-labelledby="today-plan-title"><div className="section-heading compact"><div><p className="eyebrow">오늘의 학습 계획</p><h2 id="today-plan-title">지금 바로 할 일</h2><p>가장 중요한 다음 행동을 먼저 선택하세요.</p></div><Link className="text-link" href="/reviews">복습 전체 보기</Link></div><div className="today-plan-grid"><article className="today-plan-card today-plan-card-primary"><span className="badge">오늘 목표</span><h3>{remaining ? `${remaining}문제를 더 풀어보세요` : "오늘의 목표를 완료했습니다"}</h3><ProgressBar value={plan.completionPercent} label="오늘 문제 목표" /><p>목표 {plan.settings.dailyQuestionGoal}문제 중 {plan.completedQuestions}문제를 완료했습니다.</p><ActionButton href={recommendation?.href ?? (current ? `/practice/${current.courseSlug}` : "/courses")} variant="primary">문제풀이 시작</ActionButton></article><article className="today-plan-card"><span className="badge">복습</span><h3>{plan.reviewSummary.dueCount}개 복습 예정</h3><p>틀린 문제와 취약 개념을 다시 확인하세요.</p><Link className="text-link" href="/reviews">복습 시작하기</Link></article><article className="today-plan-card"><span className="badge">추천 학습</span><h3>{recommendation?.title ?? "학습을 시작해보세요"}</h3><p>{recommendation?.reason ?? "과정을 선택하면 학습 기록에 맞는 추천을 받을 수 있습니다."}</p><Link className="text-link" href={recommendation?.href ?? "/courses"}>추천 학습 보기</Link></article><article className="today-plan-card today-plan-settings-card"><span className="badge">학습 설정</span><h3>오늘 목표 조정</h3><p>문제 수와 학습 시간을 내 일정에 맞춰 설정하세요.</p><LearningSettingsForm dailyQuestionGoal={plan.settings.dailyQuestionGoal} dailyStudyMinutes={plan.settings.dailyStudyMinutes} /></article></div></section>
    <section className="section-block" aria-labelledby="active-courses-title"><div className="section-heading compact"><div><p className="eyebrow">이어서 학습</p><h2 id="active-courses-title">진행 중인 과정</h2></div><Link className="text-link" href="/my-courses">내 과정 전체 보기</Link></div>{active.length ? <div className="enrollment-grid">{active.map((enrollment) => <EnrollmentCard enrollment={enrollment} key={enrollment.id} />)}</div> : <div className="empty-state"><strong>진행 중인 과정이 없습니다.</strong><p>과정 목록에서 학습할 과정을 선택해보세요.</p><ActionButton href="/courses" variant="dark">과정 둘러보기</ActionButton></div>}</section>
    <section className="section-block" aria-labelledby="summary-title"><div className="section-heading compact"><div><p className="eyebrow">학습 기록</p><h2 id="summary-title">학습 현황 한눈에 보기</h2></div><Link className="text-link" href="/analytics">상세 분석 보기</Link></div><div className="stats-grid"><Stat label="진행 중 과정" value={active.length} detail="이어서 학습할 과정" /><Stat label="등록 과정" value={enrollments.length} detail="내 과정" /><Stat label="오늘 완료" value={plan.completedQuestions} detail={`목표 ${plan.settings.dailyQuestionGoal}문제`} /><Stat label="복습 대기" value={plan.reviewSummary.dueCount} detail="예정된 복습" href="/reviews" /></div></section></div></main>;
}

function EnrollmentCard({ enrollment }: { enrollment: Enrollment }) { return <article className="enrollment-card"><div className="course-card-top"><span className="course-code">{enrollment.groupName}</span><span className="badge">학습 중</span></div><h3>{enrollment.courseName}</h3><ProgressBar value={enrollment.progressPercent} label="과정 진도" /><dl className="metric-list"><div><dt>현재 단계</dt><dd>{enrollment.currentLevel} / {enrollment.totalLevels}</dd></div><div><dt>정답률</dt><dd>{enrollment.accuracy === null ? "기록 없음" : `${enrollment.accuracy}%`}</dd></div><div><dt>최근 학습</dt><dd>{enrollment.lastStudiedAt ? new Date(enrollment.lastStudiedAt).toLocaleDateString("ko-KR") : "시작 전"}</dd></div><div><dt>이론 진도</dt><dd>{enrollment.theoryProgressPercent ?? 0}%</dd></div></dl><div className="card-actions"><ActionButton href={`/learn/${enrollment.courseSlug}`} variant="primary">학습 이어가기</ActionButton><ActionButton href={`/practice/${enrollment.courseSlug}?random=1&count=10`} variant="ghost">문제 풀기</ActionButton></div></article>; }
function Stat({ label, value, detail, href }: { label: string; value: number; detail: string; href?: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{href ? <Link className="stat-card-action" href={href}>{detail}</Link> : detail}</small></div>; }
async function safe<T>(loader: () => Promise<T>, fallback: T): Promise<T> { try { return await loader(); } catch { return fallback; } }
function emptyPlan() { return { settings: { dailyQuestionGoal: 10, dailyStudyMinutes: 30 }, completedQuestions: 0, completionPercent: 0, reviewSummary: { dueCount: 0, overdueCount: 0, estimatedMinutes: 0, completionPercent: 0, byCourse: [] }, recommendations: [] }; }
