-- GENERATED from db/postgres/schema-manifest.json.
-- Server-only access lockdown. Production execution requires explicit approval.
BEGIN;

-- Browser clients must not access application tables through the Data API.
REVOKE ALL PRIVILEGES ON TABLE public."app_schema_migrations" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."app_schema_migrations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."course_groups" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."course_groups" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."isms_standards" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."isms_standards" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."legal_articles" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."legal_articles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."privacy_impact_assessment_items" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."privacy_impact_assessment_items" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."risk_calculation_methods" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."risk_calculation_methods" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."roles" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."roles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."secure_coding_weaknesses" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."secure_coding_weaknesses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."users" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."admin_audit_logs" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."admin_audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."courses" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."courses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."isms_defect_cases" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."isms_defect_cases" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."legal_article_versions" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."legal_article_versions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."questions" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."questions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."risk_grade_criteria" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."risk_grade_criteria" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_learning_settings" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_learning_settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."ai_generation_records" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."ai_generation_records" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."ai_specialized_generation_records" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."ai_specialized_generation_records" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."audit_logs" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."bookmarks" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."bookmarks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."content_bookmarks" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."content_bookmarks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."content_course_links" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."content_course_links" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."content_question_links" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."content_question_links" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."content_revisions" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."content_revisions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."course_specializations" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."course_specializations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."curriculum_trees" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."curriculum_trees" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."learning_activities" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."learning_activities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."levels" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."levels" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."mock_exams" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."mock_exams" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."privacy_assessment_scenarios" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."privacy_assessment_scenarios" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_attempts" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_attempts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_choices" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_choices" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_courses" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_courses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_reports" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_reports" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_versions" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_versions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."review_schedules" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."review_schedules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."risk_scenarios" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."risk_scenarios" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."secure_code_samples" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."secure_code_samples" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."subjects" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."subjects" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_course_enrollments" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_course_enrollments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_roles" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_roles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."written_answer_rules" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."written_answer_rules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."ai_reviewed_contents" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."ai_reviewed_contents" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."ai_specialized_reviews" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."ai_specialized_reviews" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."code_analysis_answers" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."code_analysis_answers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."curriculum_nodes" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."curriculum_nodes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."level_contents" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."level_contents" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."mock_exam_attempts" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."mock_exam_attempts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."mock_exam_sections" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."mock_exam_sections" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."privacy_assessment_answers" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."privacy_assessment_answers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."privacy_flow_nodes" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."privacy_flow_nodes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_subjects" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_subjects" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."risk_register_items" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."risk_register_items" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."secure_code_grading_rules" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."secure_code_grading_rules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."topics" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."topics" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_level_progress" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_level_progress" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."wrong_notes" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."wrong_notes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."learning_units" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."learning_units" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."lectures" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."lectures" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."mock_exam_answers" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."mock_exam_answers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."mock_exam_questions" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."mock_exam_questions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."privacy_flow_edges" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."privacy_flow_edges" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."question_topics" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."question_topics" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_progress" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_progress" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."lecture_bookmarks" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."lecture_bookmarks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."lecture_notes" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."lecture_notes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."lecture_progress" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."lecture_progress" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."lessons" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."lessons" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."audio_contents" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."audio_contents" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."user_lesson_progress" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."user_lesson_progress" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."audio_progress" FROM PUBLIC, anon, authenticated;
ALTER TABLE public."audio_progress" ENABLE ROW LEVEL SECURITY;

-- Keep future postgres-owned objects closed unless a reviewed migration grants access.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL PRIVILEGES ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;

INSERT INTO public.app_schema_migrations (id, checksum)
VALUES ('0002_server_only_rls_lockdown', 'server-only-lockdown-001')
ON CONFLICT (id) DO NOTHING;

COMMIT;
